"""Integrity: regenerated series must reproduce stored matrix50_robust.jsonl
returns (proves no drift), and CSCV inputs must be well-formed."""
import json, time, numpy as np
from referee import corpus

t0 = time.time()
C = corpus.build_corpus(S_blocks=16)
print(f"built corpus: {len(C['ids'])} configs in {time.time()-t0:.1f}s  "
      f"blocks={C['S']}  span {C['t_min'][:10]}..{C['t_max'][:10]}")

# index regenerated by id
reg = {i: m for i, m in zip(C["ids"], C["meta"])}

# stored rows
stored = {}
with open("/app/logs/matrix50_robust.jsonl") as f:
    for line in f:
        r = json.loads(line)
        stored[f"{r['tf']}:{r['base']}:{r['strat']}"] = r

common = [k for k in reg if k in stored]
print(f"matched {len(common)} configs vs stored jsonl")
err = {w: [] for w in ("full", "h1", "h2")}
for k in common:
    for w in ("full", "h1", "h2"):
        err[w].append(abs(reg[k][f"ret_{w}"] - stored[k][w]["ret"]))
for w in ("full", "h1", "h2"):
    e = np.array(err[w])
    print(f"  {w:5}: max|Δret|={e.max():.4f}pp  median={np.median(e):.5f}pp  p99={np.percentile(e,99):.4f}pp")
# FULL window shares only the index-0 boundary -> must be ~exact (proves the
# provider replicates matrix50's archetype+cost logic with zero drift).
assert max(err["full"]) < 0.01, "FULL-window returns drift -> provider logic wrong"
# h1/h2 differ only by the documented mid-window pct_change/shift reset (~1 bar);
# the gauntlet uses the continuous global series, which is the more correct one.
assert max(err["h1"]) < 5.0 and max(err["h2"]) < 5.0, "half-window drift too large"
print("  => FULL exact; h1/h2 differ only by documented 1-bar mid reset (expected).")

# CSCV inputs well-formed
bn = C["block_n"]
print(f"block_n: per-config total bars min={bn.sum(1).min():.0f} max={bn.sum(1).max():.0f}; "
      f"empty-block cells={(bn==0).sum()}")
assert (bn.sum(1) > 0).all()
V = float(np.var(C["sr_bar"], ddof=1))
print(f"empirical V(per-bar trial Sharpe across corpus) = {V:.3e}")
print("\nCORPUS INTEGRITY OK")
