/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppCustomizeRouteImport } from './routes/app.customize'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppMarketsRouteImport } from './routes/app.markets'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppPricingRouteImport } from './routes/app.pricing'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSignalsRouteImport } from './routes/app.signals'
import { Route as StudioBacktestsRouteImport } from './routes/studio.backtests'
import { Route as StudioCopilotRouteImport } from './routes/studio.copilot'
import { Route as StudioDocsRouteImport } from './routes/studio.docs'
import { Route as StudioEarningsRouteImport } from './routes/studio.earnings'
import { Route as StudioHealthRouteImport } from './routes/studio.health'
import { Route as StudioHomeRouteImport } from './routes/studio.home'
import { Route as StudioInstrumentsRouteImport } from './routes/studio.instruments'
import { Route as StudioLiveRouteImport } from './routes/studio.live'
import { Route as StudioMlRouteImport } from './routes/studio.ml'
import { Route as StudioPricingRouteImport } from './routes/studio.pricing'
import { Route as StudioSettingsRouteImport } from './routes/studio.settings'
import { Route as StudioSignalsRouteImport } from './routes/studio.signals'
import { Route as StudioStrategiesRouteImport } from './routes/studio.strategies'
import { Route as StudioSubmissionsRouteImport } from './routes/studio.submissions'
import { Route as StudioWalkforwardRouteImport } from './routes/studio.walkforward'
import { Route as AppShareCardIdRouteImport } from './routes/app.share.$cardId'
import { Route as AppSignalIdRouteImport } from './routes/app.signal.$id'
import { Route as AppStrategyIdRouteImport } from './routes/app.strategy.$id'
import { Route as StudioBacktestsStrategyIdRouteImport } from './routes/studio.backtests.$strategyId'
import { Route as StudioBuilderIdRouteImport } from './routes/studio.builder.$id'
import { Route as StudioStrategyIdRouteImport } from './routes/studio.strategy.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomizeRoute = AppCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const StudioBacktestsRoute = StudioBacktestsRouteImport.update({
  id: '/backtests',
  path: '/backtests',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCopilotRoute = StudioCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => StudioRoute,
} as any)
const StudioDocsRoute = StudioDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => StudioRoute,
} as any)
const StudioEarningsRoute = StudioEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioHealthRoute = StudioHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => StudioRoute,
} as any)
const StudioHomeRoute = StudioHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => StudioRoute,
} as any)
const StudioInstrumentsRoute = StudioInstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLiveRoute = StudioLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMlRoute = StudioMlRouteImport.update({
  id: '/ml',
  path: '/ml',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPricingRoute = StudioPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSignalsRoute = StudioSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => StudioRoute,
} as any)
const StudioStrategiesRoute = StudioStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSubmissionsRoute = StudioSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => StudioRoute,
} as any)
const StudioWalkforwardRoute = StudioWalkforwardRouteImport.update({
  id: '/walkforward',
  path: '/walkforward',
  getParentRoute: () => StudioRoute,
} as any)
const AppShareCardIdRoute = AppShareCardIdRouteImport.update({
  id: '/share/$cardId',
  path: '/share/$cardId',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalIdRoute = AppSignalIdRouteImport.update({
  id: '/signal/$id',
  path: '/signal/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategyIdRoute = AppStrategyIdRouteImport.update({
  id: '/strategy/$id',
  path: '/strategy/$id',
  getParentRoute: () => AppRoute,
} as any)
const StudioBacktestsStrategyIdRoute =
  StudioBacktestsStrategyIdRouteImport.update({
    id: '/$strategyId',
    path: '/$strategyId',
    getParentRoute: () => StudioBacktestsRoute,
  } as any)
const StudioBuilderIdRoute = StudioBuilderIdRouteImport.update({
  id: '/builder/$id',
  path: '/builder/$id',
  getParentRoute: () => StudioRoute,
} as any)
const StudioStrategyIdRoute = StudioStrategyIdRouteImport.update({
  id: '/strategy/$id',
  path: '/strategy/$id',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/agent': typeof AppAgentRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/customize': typeof AppCustomizeRoute
  '/app/help': typeof AppHelpRoute
  '/app/home': typeof AppHomeRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/studio/backtests': typeof StudioBacktestsRouteWithChildren
  '/studio/copilot': typeof StudioCopilotRoute
  '/studio/docs': typeof StudioDocsRoute
  '/studio/earnings': typeof StudioEarningsRoute
  '/studio/health': typeof StudioHealthRoute
  '/studio/home': typeof StudioHomeRoute
  '/studio/instruments': typeof StudioInstrumentsRoute
  '/studio/live': typeof StudioLiveRoute
  '/studio/ml': typeof StudioMlRoute
  '/studio/pricing': typeof StudioPricingRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/signals': typeof StudioSignalsRoute
  '/studio/strategies': typeof StudioStrategiesRoute
  '/studio/submissions': typeof StudioSubmissionsRoute
  '/studio/walkforward': typeof StudioWalkforwardRoute
  '/app/share/$cardId': typeof AppShareCardIdRoute
  '/app/signal/$id': typeof AppSignalIdRoute
  '/app/strategy/$id': typeof AppStrategyIdRoute
  '/studio/backtests/$strategyId': typeof StudioBacktestsStrategyIdRoute
  '/studio/builder/$id': typeof StudioBuilderIdRoute
  '/studio/strategy/$id': typeof StudioStrategyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/agent': typeof AppAgentRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/customize': typeof AppCustomizeRoute
  '/app/help': typeof AppHelpRoute
  '/app/home': typeof AppHomeRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/studio/backtests': typeof StudioBacktestsRouteWithChildren
  '/studio/copilot': typeof StudioCopilotRoute
  '/studio/docs': typeof StudioDocsRoute
  '/studio/earnings': typeof StudioEarningsRoute
  '/studio/health': typeof StudioHealthRoute
  '/studio/home': typeof StudioHomeRoute
  '/studio/instruments': typeof StudioInstrumentsRoute
  '/studio/live': typeof StudioLiveRoute
  '/studio/ml': typeof StudioMlRoute
  '/studio/pricing': typeof StudioPricingRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/signals': typeof StudioSignalsRoute
  '/studio/strategies': typeof StudioStrategiesRoute
  '/studio/submissions': typeof StudioSubmissionsRoute
  '/studio/walkforward': typeof StudioWalkforwardRoute
  '/app/share/$cardId': typeof AppShareCardIdRoute
  '/app/signal/$id': typeof AppSignalIdRoute
  '/app/strategy/$id': typeof AppStrategyIdRoute
  '/studio/backtests/$strategyId': typeof StudioBacktestsStrategyIdRoute
  '/studio/builder/$id': typeof StudioBuilderIdRoute
  '/studio/strategy/$id': typeof StudioStrategyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/agent': typeof AppAgentRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/customize': typeof AppCustomizeRoute
  '/app/help': typeof AppHelpRoute
  '/app/home': typeof AppHomeRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/studio/backtests': typeof StudioBacktestsRouteWithChildren
  '/studio/copilot': typeof StudioCopilotRoute
  '/studio/docs': typeof StudioDocsRoute
  '/studio/earnings': typeof StudioEarningsRoute
  '/studio/health': typeof StudioHealthRoute
  '/studio/home': typeof StudioHomeRoute
  '/studio/instruments': typeof StudioInstrumentsRoute
  '/studio/live': typeof StudioLiveRoute
  '/studio/ml': typeof StudioMlRoute
  '/studio/pricing': typeof StudioPricingRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/signals': typeof StudioSignalsRoute
  '/studio/strategies': typeof StudioStrategiesRoute
  '/studio/submissions': typeof StudioSubmissionsRoute
  '/studio/walkforward': typeof StudioWalkforwardRoute
  '/app/share/$cardId': typeof AppShareCardIdRoute
  '/app/signal/$id': typeof AppSignalIdRoute
  '/app/strategy/$id': typeof AppStrategyIdRoute
  '/studio/backtests/$strategyId': typeof StudioBacktestsStrategyIdRoute
  '/studio/builder/$id': typeof StudioBuilderIdRoute
  '/studio/strategy/$id': typeof StudioStrategyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/studio'
    | '/app/admin'
    | '/app/agent'
    | '/app/catalog'
    | '/app/customize'
    | '/app/help'
    | '/app/home'
    | '/app/markets'
    | '/app/performance'
    | '/app/pricing'
    | '/app/settings'
    | '/app/signals'
    | '/studio/backtests'
    | '/studio/copilot'
    | '/studio/docs'
    | '/studio/earnings'
    | '/studio/health'
    | '/studio/home'
    | '/studio/instruments'
    | '/studio/live'
    | '/studio/ml'
    | '/studio/pricing'
    | '/studio/settings'
    | '/studio/signals'
    | '/studio/strategies'
    | '/studio/submissions'
    | '/studio/walkforward'
    | '/app/share/$cardId'
    | '/app/signal/$id'
    | '/app/strategy/$id'
    | '/studio/backtests/$strategyId'
    | '/studio/builder/$id'
    | '/studio/strategy/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/studio'
    | '/app/admin'
    | '/app/agent'
    | '/app/catalog'
    | '/app/customize'
    | '/app/help'
    | '/app/home'
    | '/app/markets'
    | '/app/performance'
    | '/app/pricing'
    | '/app/settings'
    | '/app/signals'
    | '/studio/backtests'
    | '/studio/copilot'
    | '/studio/docs'
    | '/studio/earnings'
    | '/studio/health'
    | '/studio/home'
    | '/studio/instruments'
    | '/studio/live'
    | '/studio/ml'
    | '/studio/pricing'
    | '/studio/settings'
    | '/studio/signals'
    | '/studio/strategies'
    | '/studio/submissions'
    | '/studio/walkforward'
    | '/app/share/$cardId'
    | '/app/signal/$id'
    | '/app/strategy/$id'
    | '/studio/backtests/$strategyId'
    | '/studio/builder/$id'
    | '/studio/strategy/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/studio'
    | '/app/admin'
    | '/app/agent'
    | '/app/catalog'
    | '/app/customize'
    | '/app/help'
    | '/app/home'
    | '/app/markets'
    | '/app/performance'
    | '/app/pricing'
    | '/app/settings'
    | '/app/signals'
    | '/studio/backtests'
    | '/studio/copilot'
    | '/studio/docs'
    | '/studio/earnings'
    | '/studio/health'
    | '/studio/home'
    | '/studio/instruments'
    | '/studio/live'
    | '/studio/ml'
    | '/studio/pricing'
    | '/studio/settings'
    | '/studio/signals'
    | '/studio/strategies'
    | '/studio/submissions'
    | '/studio/walkforward'
    | '/app/share/$cardId'
    | '/app/signal/$id'
    | '/app/strategy/$id'
    | '/studio/backtests/$strategyId'
    | '/studio/builder/$id'
    | '/studio/strategy/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customize': {
      id: '/app/customize'
      path: '/customize'
      fullPath: '/app/customize'
      preLoaderRoute: typeof AppCustomizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/markets': {
      id: '/app/markets'
      path: '/markets'
      fullPath: '/app/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/signals': {
      id: '/app/signals'
      path: '/signals'
      fullPath: '/app/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/studio/backtests': {
      id: '/studio/backtests'
      path: '/backtests'
      fullPath: '/studio/backtests'
      preLoaderRoute: typeof StudioBacktestsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/copilot': {
      id: '/studio/copilot'
      path: '/copilot'
      fullPath: '/studio/copilot'
      preLoaderRoute: typeof StudioCopilotRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/docs': {
      id: '/studio/docs'
      path: '/docs'
      fullPath: '/studio/docs'
      preLoaderRoute: typeof StudioDocsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/earnings': {
      id: '/studio/earnings'
      path: '/earnings'
      fullPath: '/studio/earnings'
      preLoaderRoute: typeof StudioEarningsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/health': {
      id: '/studio/health'
      path: '/health'
      fullPath: '/studio/health'
      preLoaderRoute: typeof StudioHealthRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/home': {
      id: '/studio/home'
      path: '/home'
      fullPath: '/studio/home'
      preLoaderRoute: typeof StudioHomeRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/instruments': {
      id: '/studio/instruments'
      path: '/instruments'
      fullPath: '/studio/instruments'
      preLoaderRoute: typeof StudioInstrumentsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/live': {
      id: '/studio/live'
      path: '/live'
      fullPath: '/studio/live'
      preLoaderRoute: typeof StudioLiveRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/ml': {
      id: '/studio/ml'
      path: '/ml'
      fullPath: '/studio/ml'
      preLoaderRoute: typeof StudioMlRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/pricing': {
      id: '/studio/pricing'
      path: '/pricing'
      fullPath: '/studio/pricing'
      preLoaderRoute: typeof StudioPricingRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/signals': {
      id: '/studio/signals'
      path: '/signals'
      fullPath: '/studio/signals'
      preLoaderRoute: typeof StudioSignalsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/strategies': {
      id: '/studio/strategies'
      path: '/strategies'
      fullPath: '/studio/strategies'
      preLoaderRoute: typeof StudioStrategiesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/submissions': {
      id: '/studio/submissions'
      path: '/submissions'
      fullPath: '/studio/submissions'
      preLoaderRoute: typeof StudioSubmissionsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/walkforward': {
      id: '/studio/walkforward'
      path: '/walkforward'
      fullPath: '/studio/walkforward'
      preLoaderRoute: typeof StudioWalkforwardRouteImport
      parentRoute: typeof StudioRoute
    }
    '/app/share/$cardId': {
      id: '/app/share/$cardId'
      path: '/share/$cardId'
      fullPath: '/app/share/$cardId'
      preLoaderRoute: typeof AppShareCardIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/signal/$id': {
      id: '/app/signal/$id'
      path: '/signal/$id'
      fullPath: '/app/signal/$id'
      preLoaderRoute: typeof AppSignalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/strategy/$id': {
      id: '/app/strategy/$id'
      path: '/strategy/$id'
      fullPath: '/app/strategy/$id'
      preLoaderRoute: typeof AppStrategyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/studio/backtests/$strategyId': {
      id: '/studio/backtests/$strategyId'
      path: '/$strategyId'
      fullPath: '/studio/backtests/$strategyId'
      preLoaderRoute: typeof StudioBacktestsStrategyIdRouteImport
      parentRoute: typeof StudioBacktestsRoute
    }
    '/studio/builder/$id': {
      id: '/studio/builder/$id'
      path: '/builder/$id'
      fullPath: '/studio/builder/$id'
      preLoaderRoute: typeof StudioBuilderIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/strategy/$id': {
      id: '/studio/strategy/$id'
      path: '/strategy/$id'
      fullPath: '/studio/strategy/$id'
      preLoaderRoute: typeof StudioStrategyIdRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAgentRoute: typeof AppAgentRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppCustomizeRoute: typeof AppCustomizeRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPricingRoute: typeof AppPricingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppShareCardIdRoute: typeof AppShareCardIdRoute
  AppSignalIdRoute: typeof AppSignalIdRoute
  AppStrategyIdRoute: typeof AppStrategyIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAgentRoute: AppAgentRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppCustomizeRoute: AppCustomizeRoute,
  AppHelpRoute: AppHelpRoute,
  AppHomeRoute: AppHomeRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPricingRoute: AppPricingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppShareCardIdRoute: AppShareCardIdRoute,
  AppSignalIdRoute: AppSignalIdRoute,
  AppStrategyIdRoute: AppStrategyIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface StudioBacktestsRouteChildren {
  StudioBacktestsStrategyIdRoute: typeof StudioBacktestsStrategyIdRoute
}

const StudioBacktestsRouteChildren: StudioBacktestsRouteChildren = {
  StudioBacktestsStrategyIdRoute: StudioBacktestsStrategyIdRoute,
}

const StudioBacktestsRouteWithChildren = StudioBacktestsRoute._addFileChildren(
  StudioBacktestsRouteChildren,
)

interface StudioRouteChildren {
  StudioBacktestsRoute: typeof StudioBacktestsRouteWithChildren
  StudioCopilotRoute: typeof StudioCopilotRoute
  StudioDocsRoute: typeof StudioDocsRoute
  StudioEarningsRoute: typeof StudioEarningsRoute
  StudioHealthRoute: typeof StudioHealthRoute
  StudioHomeRoute: typeof StudioHomeRoute
  StudioInstrumentsRoute: typeof StudioInstrumentsRoute
  StudioLiveRoute: typeof StudioLiveRoute
  StudioMlRoute: typeof StudioMlRoute
  StudioPricingRoute: typeof StudioPricingRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioSignalsRoute: typeof StudioSignalsRoute
  StudioStrategiesRoute: typeof StudioStrategiesRoute
  StudioSubmissionsRoute: typeof StudioSubmissionsRoute
  StudioWalkforwardRoute: typeof StudioWalkforwardRoute
  StudioBuilderIdRoute: typeof StudioBuilderIdRoute
  StudioStrategyIdRoute: typeof StudioStrategyIdRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioBacktestsRoute: StudioBacktestsRouteWithChildren,
  StudioCopilotRoute: StudioCopilotRoute,
  StudioDocsRoute: StudioDocsRoute,
  StudioEarningsRoute: StudioEarningsRoute,
  StudioHealthRoute: StudioHealthRoute,
  StudioHomeRoute: StudioHomeRoute,
  StudioInstrumentsRoute: StudioInstrumentsRoute,
  StudioLiveRoute: StudioLiveRoute,
  StudioMlRoute: StudioMlRoute,
  StudioPricingRoute: StudioPricingRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioSignalsRoute: StudioSignalsRoute,
  StudioStrategiesRoute: StudioStrategiesRoute,
  StudioSubmissionsRoute: StudioSubmissionsRoute,
  StudioWalkforwardRoute: StudioWalkforwardRoute,
  StudioBuilderIdRoute: StudioBuilderIdRoute,
  StudioStrategyIdRoute: StudioStrategyIdRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
