/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioHomeRouteImport } from './routes/studio.home'
import { Route as StudioEarningsRouteImport } from './routes/studio.earnings'
import { Route as StudioDocsRouteImport } from './routes/studio.docs'
import { Route as AppSignalsRouteImport } from './routes/app.signals'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppStrategyIdRouteImport } from './routes/app.strategy.$id'
import { Route as AppSignalIdRouteImport } from './routes/app.signal.$id'
import { Route as AppShareCardIdRouteImport } from './routes/app.share.$cardId'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioHomeRoute = StudioHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => StudioRoute,
} as any)
const StudioEarningsRoute = StudioEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioDocsRoute = StudioDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => StudioRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategyIdRoute = AppStrategyIdRouteImport.update({
  id: '/strategy/$id',
  path: '/strategy/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalIdRoute = AppSignalIdRouteImport.update({
  id: '/signal/$id',
  path: '/signal/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppShareCardIdRoute = AppShareCardIdRouteImport.update({
  id: '/share/$cardId',
  path: '/share/$cardId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/app/catalog': typeof AppCatalogRoute
  '/app/home': typeof AppHomeRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/studio/docs': typeof StudioDocsRoute
  '/studio/earnings': typeof StudioEarningsRoute
  '/studio/home': typeof StudioHomeRoute
  '/app/share/$cardId': typeof AppShareCardIdRoute
  '/app/signal/$id': typeof AppSignalIdRoute
  '/app/strategy/$id': typeof AppStrategyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/app/catalog': typeof AppCatalogRoute
  '/app/home': typeof AppHomeRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/studio/docs': typeof StudioDocsRoute
  '/studio/earnings': typeof StudioEarningsRoute
  '/studio/home': typeof StudioHomeRoute
  '/app/share/$cardId': typeof AppShareCardIdRoute
  '/app/signal/$id': typeof AppSignalIdRoute
  '/app/strategy/$id': typeof AppStrategyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/app/catalog': typeof AppCatalogRoute
  '/app/home': typeof AppHomeRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/studio/docs': typeof StudioDocsRoute
  '/studio/earnings': typeof StudioEarningsRoute
  '/studio/home': typeof StudioHomeRoute
  '/app/share/$cardId': typeof AppShareCardIdRoute
  '/app/signal/$id': typeof AppSignalIdRoute
  '/app/strategy/$id': typeof AppStrategyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/studio'
    | '/app/catalog'
    | '/app/home'
    | '/app/performance'
    | '/app/settings'
    | '/app/signals'
    | '/studio/docs'
    | '/studio/earnings'
    | '/studio/home'
    | '/app/share/$cardId'
    | '/app/signal/$id'
    | '/app/strategy/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/studio'
    | '/app/catalog'
    | '/app/home'
    | '/app/performance'
    | '/app/settings'
    | '/app/signals'
    | '/studio/docs'
    | '/studio/earnings'
    | '/studio/home'
    | '/app/share/$cardId'
    | '/app/signal/$id'
    | '/app/strategy/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/studio'
    | '/app/catalog'
    | '/app/home'
    | '/app/performance'
    | '/app/settings'
    | '/app/signals'
    | '/studio/docs'
    | '/studio/earnings'
    | '/studio/home'
    | '/app/share/$cardId'
    | '/app/signal/$id'
    | '/app/strategy/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/home': {
      id: '/studio/home'
      path: '/home'
      fullPath: '/studio/home'
      preLoaderRoute: typeof StudioHomeRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/earnings': {
      id: '/studio/earnings'
      path: '/earnings'
      fullPath: '/studio/earnings'
      preLoaderRoute: typeof StudioEarningsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/docs': {
      id: '/studio/docs'
      path: '/docs'
      fullPath: '/studio/docs'
      preLoaderRoute: typeof StudioDocsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/app/signals': {
      id: '/app/signals'
      path: '/signals'
      fullPath: '/app/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/strategy/$id': {
      id: '/app/strategy/$id'
      path: '/strategy/$id'
      fullPath: '/app/strategy/$id'
      preLoaderRoute: typeof AppStrategyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/signal/$id': {
      id: '/app/signal/$id'
      path: '/signal/$id'
      fullPath: '/app/signal/$id'
      preLoaderRoute: typeof AppSignalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/share/$cardId': {
      id: '/app/share/$cardId'
      path: '/share/$cardId'
      fullPath: '/app/share/$cardId'
      preLoaderRoute: typeof AppShareCardIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCatalogRoute: typeof AppCatalogRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppShareCardIdRoute: typeof AppShareCardIdRoute
  AppSignalIdRoute: typeof AppSignalIdRoute
  AppStrategyIdRoute: typeof AppStrategyIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogRoute: AppCatalogRoute,
  AppHomeRoute: AppHomeRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppShareCardIdRoute: AppShareCardIdRoute,
  AppSignalIdRoute: AppSignalIdRoute,
  AppStrategyIdRoute: AppStrategyIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface StudioRouteChildren {
  StudioDocsRoute: typeof StudioDocsRoute
  StudioEarningsRoute: typeof StudioEarningsRoute
  StudioHomeRoute: typeof StudioHomeRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioDocsRoute: StudioDocsRoute,
  StudioEarningsRoute: StudioEarningsRoute,
  StudioHomeRoute: StudioHomeRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
